# Generated by Django 3.1.6 on 2021-02-27 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_auto_20210227_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='image_app.categorytag'),
        ),
    ]
